services:
    frontend:
        build: ./frontend
        container_name: frontend
        expose:
            - "3000"
        ports:
            - "3000:3000"
        depends_on:
            - "product"
            - "gateway"
        networks:
            - kbe
    product:
        build: ./product
        container_name: product
        expose:
            - "8084"
        ports:
            - "8084:8084"
        environment:
            MYSQL_HOST: product-mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DB: productdb
            SPRING_PROFILES_ACTIVE: docker
            MONGO_HOST: product-mongo
        depends_on:
            - 'product-db-mysql'
            - 'product-db-mongo'
        networks:
            - kbe

    product-db-mysql:
        image: mysql:5.7
        container_name: product-mysql
        ports:
            - "3305:3306"
        networks:
            - kbe
        volumes:
            - kbe-mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: productdb

    product-db-mongo:
        image: mongo:5.0.7
        container_name: product-mongo
        ports:
            - "27016:27017"
        networks:
            - kbe
        volumes:
            - kbe-mongo-data:/data/db

    gateway:
        build: ./gateway
        container_name: gateway
        expose:
            - "8000"
        ports:
            - "8000:8000"
        environment:
            SPRING_PROFILES_ACTIVE: docker
            PRODUCT_HOST: product
        # depends on: rabbitmq
        networks:
            - kbe

volumes:
    kbe-mysql-data:
    kbe-mongo-data:

networks:
    kbe:
        driver: bridge